---
- name: Install requirements
  become: true
  yum:
    update_cache: true
    name: epel-release
    state: present
- name: Import nux repo key
  become: true
  rpm_key:
    key: http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
    state: present
- name: Install nux repo
  become: true
  yum:
    name: "{{ nux_repo }}"
    state: present
- name: Install ffmpeg plus codec requirements
  become: true
  yum:
    update_cache: true
    name: ["ffmpeg", "ffmpeg-devel", "x264", "x265"]
    state: present
